### ISSUE TITLE
Membuat dokumentasi Mock

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#1]
Untuk kebutuhan pihak Sucor bisa melaksanakan sendiri Mock, maka diperlukan dokumentasi bagaimana cara-cara setting dan menjalankan OLT secara mock

Dokumentasi dibuat secara step-by-step dan detail

**Comment by kassle** [comment]
dokumen cara mock
file ada di slack https://netzme.slack.com/files/kassle/F02UTLH5V/how-to-mock-step-by-step-procedure.doc

**Comment by hendrisulistiono** [comment]
Data sudah saya gabungkan dengan dokumen-dokumen yang lain, yaitu di smb://10.0.0.15/documents/hendri/Sucorinvest%20Doc
