### ISSUE TITLE
Mengumpulkan dan merapikan dokumentasi sucor

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#11]

**Comment by hendrisulistiono** [comment]
Untuk kebutuhan training dengan sucor diperlukan untuk mengumpulkan dokumentasi, misalnya manual program, troubleshooting, dll.

Beberapa dokumentasi sudah dikumpulkan di folder smb://10.0.0.15/documents/hendri/Sucorinvest%20Doc, akan tetapi diperlukan kolaborasi untuk check masing-masing dokumen, apakah masih valid atau tidak.
1. Tambahkan dokumen troubleshooting di smb://10.0.0.15/documents/hendri/Sucorinvest Doc/unfinish/troubleshooting.html, jika ada yang perlu ditambahkan
2. Periksa dokumen yang berhubungan dengan kita dan yang berada di folder smb://10.0.0.15/documents/hendri/Sucorinvest%20Doc. Bagi yang sudah melakukan checking tambahkan di comment, dokumen apa saja yang sudah dicheck.

**Comment by kassle** [comment]
per tanggal 11 desember 2014 sudah di diskusikan, mohon untuk team developer untuk cek document sucorinvest di git. (repository = git.quantumfin.com/document). mohon untuk melihat setiap folder yang memiliki prefix 'check', jika ada file yang prefix-nya nama developer mohon untuk segera membereskan file tersebut.
- [x] andreas
- [x] daori
- [x] kassle
- [x] noval

**Comment by hendrisulistiono** [comment]
Dokumen sudah dikirimkan ke anton

**Comment by hendrisulistiono** [comment]
Sudah dikirim ke anton dan sedang dipelajari
