### ISSUE TITLE
Investigasi dan Penyelesaian masalah order not sent

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#12]
Sudah 2(dua) hari yakni hari Kamis 13 Nov 2014 dan Jumat 14 Nov 2014  telah terjadi status order tidak terkirim ke JATS.

Contoh ordernya adalah sebagai berikut :
https://netzme.slack.com/files/hendri/F0307C209/order_not_send-1.pdf

**Comment by cyberspaces14** [comment]
- Cek log  order di TS  dan log balasan dari jonec  dari order number 
  - [ ] 1367
  - [ ] 368
  -  [ ] 1372
  - [ ] 1406 
  - [ ] 1408
- Bila di butuhkan minta log  komputer server Jonec dari order di atas

**Comment by hendrisulistiono** [comment]
Setelah diskusi dengan pak Anton, pada saat jam 9:00 dia melihat ada order-order yang diinput sebelum jam 9  tapi belum dikirim ke JATS, akhirnya dia centang-centangin order-order tersebut kemudian dikirim melalui Basket Send Checked

Saham-saham yang tidak terkirim tersebut saham non pre opening

**Comment by GunawanIP** [comment]
coba cek dulu .. jangan2 tradernya emang naro put in basket ..

**Comment by hendrisulistiono** [comment]
Sesuai gambar yg dikirim kolom basket berisi "N"

**Comment by hendrisulistiono** [comment]
Tidak bisa ter-reproduce, akan tetapi dibetulkan sesuai dengan hasil investigasi log
