### ISSUE TITLE
Membuat GUI Order transaksi langsung ke jonec

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#13]
Dari hasil meeting untuk kebutuhan User By Pass #5, maka pendekatan yang digunakan adalah mengembangkan dari sample jonec app.

Untuk mengembangkan aplikasi tersebut berikut beberapa hal yang diperlukan :
1. Research cara mengirim order (message) melalui jonec API
2. Membuat GUI untuk order transaksi langsung ke jonec API (Buy, Sell, Amend dan Withdraw)
    - Validasi basic untuk inputan, misalnya price harus angka
    - Tidak ada rule-rule seperti order transaksi normal, misanya pengecekan nama saham, kode nasabah, approval, dll

**Comment by kassle** [comment]
to do:
- [ ] research penggunaan API jonec
  - [ ] koneksi ke jonec
  - [ ] cara mengirim order (field2 yang harus di isi)
- [ ] konektor ke jonec
- [ ] global handler untuk menampung message - message dari jonec. error, koneksi, dan message - message transaksi
- [ ] distribute message - message ke spesifik handler
- [ ] handler untuk melakukan konek ke jonec
- [ ] handler order buy sell
- [ ] handler amend
- [ ] handler withdraw

**Comment by kassle** [comment]
sehubungan dengan di putusnya kontrak, maka tidak perlu lagi di follow up
