### ISSUE TITLE
Beberapa nasabah tidak menerima confirmation letter

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#14]

**Comment by hendrisulistiono** [comment]
Laporan dari pak Luky, ada beberapa nasabah yang tidak mendapatkan informasi confirmation letter, diantaranya adalah sebagai berikut :

SITI ALFIYAH

ACHMAD IMARAH ARDIANSYAH

ENDAH DAMAY PUTRI

Tolong di check

**Comment by daori** [comment]
Pengecekan 
- SMTP (tidak masalah, sudah dicoba pake telnet)
- Config untuk FOBO dan WebAdmin

Solving Problem (pada quantumfin environment): 
- untuk update email cukud di adminuser saja pada menu edit.
- otomatis merubah ke BO pada field email

catatan : 
- pastikan load di server 10.105 tidak terlalu berat.

**Comment by hendrisulistiono** [comment]
Menurut pak iyan, user dilapangan ditanya oleh marketing apakah terima confirmation letter atau tidak, belum dicek oleh user tapi usernya sudah menjawab tidak menerima
