### ISSUE TITLE
MI tidak jalan karena exception di foreign domestik

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#15]

**Comment by hendrisulistiono** [comment]
Ada exception di MI yang menyebabkan MI tidak jalan (icon refresh terus), hal ini terjadi karena ada yg membuka foreign domestik dengan memasukkan stock yang tidak punya index atau stock yang belum ada transaksi match

**Comment by cyberspaces14** [comment]
Tidak berhasil mereproduce di local dan sudah di masukan ke production
