### ISSUE TITLE
Membuat script untuk mengecek log dan kirim email

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#16]

**Comment by hendrisulistiono** [comment]
Saat ini untuk menge-cek proses fobo jam 04.00 pagi, sukses atau tidaknya harus melakukan ssh dan melakukan cek log secara manual.

Untuk mempermudah diperlukan tools untuk melakukan pengecekan ini : 
1. Membuat script untuk mengecek log fobo 
2. Hasil dari pengecekan dikirim ke email
3. Script ini dijalankan menggunakan scheduler atau cron setiap jam 4.30 pagi

**Comment by berrywira** [comment]
Script dijalankan jam 4:35, 
output : log fobo, yang akan dikirim ke email, Noval,Hendri,Sandi,Berry.

**Comment by abufathan** [comment]
Sudah di test langsung di production sucor dan berhasil

**Comment by hendrisulistiono** [comment]
Setiap hari sudah mendapatkan email
