### ISSUE TITLE
Check client OKMA9413 apakah registrasi dari web spot

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#17]

**Comment by hendrisulistiono** [comment]
Client OKMA9413 mulai aktif tgl antara 7-8 oktober 2014

Minta tolong di chek apakah registrasi melalui webspot ?

**Comment by daori** [comment]
- User tidak terdaftar pada dbweb
- User hanya terdaftar pada dbts
  - Membuktikan user di masukan lewat BO

**Comment by hendrisulistiono** [comment]
Oke
