### ISSUE TITLE
Membuat dokumentasi switch database

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#2]
Replikasi database saat ini sudah berjalan antara server duren 3 dan elitery. Secara default duren 3 sebagai master dan elitery sebagai slave. Data di-synchronize dari master ke slave. 

Diperlukan dokumentasi cara switch konfigurasi server, agar sychronize data tetap terjaga jika terjadi master dan slave-nya berubah.
Misalnya : Secara default Duren 3 (master) dan Elitery (slave) kemudian berubah Elitery (master) dan Duren 3 (slave)

**Comment by kassle** [comment]
lokasi file dokumen:
smb://10.0.0.15/documents/hendri/Sucorinvest Doc/unfinish/how-to-switchdb-step-by-step-procedure.doc

**Comment by hendrisulistiono** [comment]
sudah selesai dirapikan lokasi dokumen di smb://10.0.0.15/documents/hendri/Sucorinvest%20Doc/MOCK
