### ISSUE TITLE
Riset tentang penggunaan *.jnlp di AppStore

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#21]
Hasil diskusi dengan pihak sucor, untuk pemakai mac rata-rata adalah client yang cukup lumayan dan kemampuan IT kurang. Sehingga ada kebutuhan bagaimana bisa memasukkan *.jnlp ke Appstore

**Comment by hendrisulistiono** [comment]
Buat @kassle, langsung di done aja dan diberi komen

**Comment by kassle** [comment]
setelah diskusi dengan @hendrisulistiono dan @kongput disepakati untuk tidak dapat memenuhi permintaan ini dikarenakan:
- untuk publish ke appstore ada fee per tahun
- dibutuhkan certificate developer id dari apple, yang memungkinkan konflik dengan java certificate yang digunakan pada aplikasi SPOT/QUEST
- tidak memungkinkan untuk memuat jnlp ke installer mac os, karena bukan file executeable
- jika di paksa untuk membuat file executeable harus include Java yang ukurannya besar
- jika include java, mac os x sendiri kurang java friendly (banyak issue yang beredar)
