### ISSUE TITLE
Review dan setting memory jvm untuk semua service java

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#3]
Untuk meng-optimalkan performance aplikasi, saat ini pihak sucor sudah meng-upgrade memory fisik beberapa server-nya.

Berikut beberapa hal yang perlu dilakukan : 
- Review service - service yang perlu dinaikkan memorynya
- Merubah setting memory jvm untuk service-service tersebut

**Comment by kassle** [comment]
- [x] check kapasitas memory pada setiap mesin
- [x] check penggunaan memory untuk setiap service, dan berapa yang sudah terpakai (info virtual, reserved, dan shared pada top)
- [x] kalkulasi peningkatan memory sesuai dengan kapasitas dan ratio penggunaan memory
- [ ] update setting memory pada launcher sesuai dengan hasil kalkulasi
- [ ] testing dan pastikan setiap service dapat running tanpa ada yang tidak kebagian memory karena setting-nya overlap
- [ ] laporkan hasil perubahan setting memory ke developer, supaya setting dapat di permanen-kan pada template aplikasi

**Comment by kassle** [comment]
SPOT:
- service squiler dan squidrive di server mobidc, sebelumnya di set menggunakan memory 1GB. bisa di naikkan menjadi squiler = 6GB dan squidrive = 4GB.
- service mig di server elitery, dibuatkan template untuk development menggunakan 4GB (tetap) karena share dengan service lainnya (MIS, dan DFsimulator). untuk production (drc) menggunakan 13GB dari sebelumnya satu config dengan development (4GB)

**Comment by kassle** [comment]
di perlukan pemindahan memory dari mesin satu ke mesin yang lain, karena ada mesin yang memory-nya berlimpah dan ada yang kekurangan.

hasil review-nya bisa di lihat pada:
folder = smb://10.0.0.15/documents/hendri/Sucorinvest Doc/unfinish
file = Memory Usage.ods

**Comment by kongput** [comment]
mengenai pemindahan memory dari mesin satu ke yang lain, apa bisa di buatkan ke issue berbeda. Karena membutuhkan pengerjaan dan koordinasi dengan pihak sucor. Supaya kerjaan lain yg berhubungan dengan review & setting jvm di issue ini bisa dilanjutkan. Gimana @kassle?

**Comment by kassle** [comment]
untuk review perubahaan setting memory sudah di hitung juga (ada di doc), itu hitungan berdasarkan kondisi memory saat ini. tapi belum di apply ke aplikasi.

**Comment by abufathan** [comment]
Setting memory launcher 
- Fobo = 1024
- Jadwal = 512
- Bogate = 512

hasilnya dapat di lihat di : https://docs.google.com/a/netzme.id/spreadsheets/d/1q89La5OXRbA3dW_3W7SYL64f7o_GJVkatjSBoJbANIE/edit#gid=902838388

**Comment by hendrisulistiono** [comment]
sudah dikirim ke pak anton
