### ISSUE TITLE
Membuat automatic forcesell

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#4]
Apabila sampai T+3 nasabah belum memenuhi kewajibannya maka akan dilakukan Suspend Buy, sedangkan jika berlanjut sampai dengan T+5 maka akan dilakukan "force sell" atas portofolio Nasabah tanpa harus meminta persetujuan dari Nasabah untuk menutup posisi hutang/kewajiban.

Karena banyaknya saham yang harus dipilih untuk dijual, maka pihak sucor membutuhkan tools agar proses ini bisa dibuat otomatis dengan memberikan kriteria-kriteria tertentu.

Dari pihak sucor akan memberikan data yang akan di proses 1 hari sekali, dan aturannya kurang lebih sebagai berikut : 

smb://10.0.0.15/documents/hendri/Sucorinvest/Forcesell

**Comment by kassle** [comment]
Pengerjaan:
- [x] Transaction Server melakukan forcesell
- [x] Fobo import data outstanding dari BO

**Comment by kassle** [comment]
untuk melakukan test forcesell bisa mengikuti dokumen:

folder = smb://10.0.0.15/documents/hendri/Sucorinvest Doc/unfinish
file = cara_test_forcesell.txt

**Comment by cyberspaces14** [comment]
Belum selesai di test. tapi secara fungsi telah di drop untuk SCR
