### ISSUE TITLE
User by pass

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#5]
Ketika terjadi masalah yang menyebabkan tidak bisa transaksi saham, pihak sucor meminta dibuatkan beberapa user yang tetap bisa melakukan transaksi dengan mem-by pass rule-rule yang sudah ada saat ini, misalnya login, approval, dll.

Hasil diskusi sementara solusi yang ditawarkan adalah
1. Menggunakan aplikasi sample yang sudah disediakan oleh jonec
2. Membuatkan aplikasi yang langsung kirim order melalui jonec

Untuk mencoba point 1 diperlukan untuk mencoba apakah aplikasi sample dari jonec bisa digunakan untuk order

**Comment by GunawanIP** [comment]
Kalau ternyata sample program point 1 nya ada .. kita gunakan program itu apa adanya dulu ..

**Comment by kassle** [comment]
di aplikasi JONEC terdapat aplikasi MessageComposer, bisa saja digunakan untuk melakukan order dan lain sebagainya. tetapi sepertinya sangat jauh sekali dari kata - kata sederhana, cepat, dan friendly.

bisa dicoba dengan melakukan:
- remote desktop ke 10.0.0.2 (user: jonec; pass: empty)
- buka file explorer ke folder C:\JONEC\JONEC71_SA\win32\bin
- jalankan EltService.bat
- jalankan JonecStartup.bat
- jalankan MessageComposer.bat

apakah mau menggunakan MessageComposer atau mau melakukan option 2 ?

**Comment by kassle** [comment]
sementara aplikasi SampleClient itu lebih command line, dan harus tau protocol FIX untuk memakainya. sepertinya SampleClient ini merupakan contoh penggunaan API untuk akses JONEC. jika option 2 di ambil, bisa melirik aplikasi ini sebagai referensi penggunaan API.

**Comment by kongput** [comment]
@kassle , mungkin besok pagi bisa didemokan ke kita semua untuk bisa menilai mana opsi yg lebih baik, sudah saya buatkan jadwal di google calendar, buat meeting besok, 14 Nov 14, jam 09:00

**Comment by hendrisulistiono** [comment]
Meeting pagi ini tanggal 14/11/2014, Erdian sudah men-demokan dari 2 kemungkinan pendekatan yang dipakai (message composer dan sample jonec app).

Dari hasil demo tersebut disimpulkan bahwa yang paling mendekati untuk dikerjakan adalah mengembangkan dari sample jonec app dan membuat GUI untuk mengirim transaksi Buy, Sell, Amend dan Withdraw
