### ISSUE TITLE
[Web Spot] Menambahkan pilihan Agama

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#6]
Description :
- Menambahkan pilihan Agama pada Data Nasabah untuk Web Spot dan Admin User
- Agama yang ditambahkan adalah Kong Hu Chu dan Lainnya
- Data yang dikirim ke BO adalah KongHuChu dan Lainnya

**Comment by cyberspaces14** [comment]
Testing 
Kong Hu Cu Pass
Lainnya Pass

**Comment by berrywira** [comment]
Deploy 
Webadmin : 1.1.13
Webportal : 1.1.11
Fobo : 2.6.1
