### ISSUE TITLE
Men-solve masalah database TS tidak nyala

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#7]
Dalam waktu 1 minggu ini sudah 2x database TS tidak nyala, yaitu ditanggal 11 dan 13 November

Diperlukan investigasi dan kemudian di fix masalahnya

**Comment by kassle** [comment]
penyebab tidak berjalan karena ada perubahan di script startup database.
todo:
- [x] fix masalah error pada startup database
- [x] fix masalah request password yang seharusnya tidak perlu pada script SwitchDB.sh

**Comment by cyberspaces14** [comment]
trusted by erdian -> tidak bisa di test

**Comment by kongput** [comment]
Ini tidak dipindahkan ke Done stage? Perlu di followup lebih lanjut sama @hendrisulistiono?
