### ISSUE TITLE
Membuat dokumentasi cara-cara test H2H

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#8]
Sesuai hasil meeting pada tanggal 11/11/2014 bahwa pihak sucor belum bisa melakukan UAT dikarenakan harus menunggu jadwal dari bank mandiri, dan informasinya bahwa paling cepat jadwalnya adalah April 2015.

Untuk itu diperlukan simulasi guna memastikan bahwa fitur H2H sudah jalan.  Simulasi dilakukan harus 1 lifecycle sehingga harus ada yang berperan sebagai bank mandiri, dengan bisa lolos simulasi ini asumsinya bahwa kita sudah lolos dari UAT.

Agar pihak sucor bisa menjalankan sendiri simulasi ini maka diperlukan :
1. Tool yang berperan sebagai bank mandiri
2. Dokumen cara install dan cara memakau tool tersebut
3. Dokumen step by step cara melakukan simulasi 1 lifecycle dan memastikan bahwa simulasi sudah berhasil

**Comment by daori** [comment]
Task 
- [x] Menyiapkan software pendukung untuk testing
- [x] Membuat documentasi penggunaan tools yang di pakai untuk test
- [x] Mendokomentasikan penggunaan tool yang di pakai

untuk testing bisa di ambil menggunakan git 
- origin    git@git.quantumfin.com:document (fetch)
  ada pada path document /sucorinvest/mandiri-host-2-host
