### ISSUE TITLE
Membuat dokumen troubleshooting house keeping tidak jalan

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/SCR#9]
Dalam kurun waktu 1 minggu ini sudah 2 kali database TS tidak nyala, salah satu efek dari problem tersebut adalah housekeeping transaksi tidak jalan dan efek selanjutnya adalah order number tidak ke-reset dan request report Trade List tidak ada isinya.

Dengan demikian diperlukan dokumen troubleshooting untuk mengatasi problem ini, hal-hal yang harus ada di dokumen tersebut adalah
1. Cara melakukan pengecekan kenapa house keeping tidak jalan
2. Cara melakukan pengecekan database TS tidak nyala (jika masalahnya itu)
3. Cara menyalakan database TS
4. Cara melakukan housekeeping manual

Jika ada masalah selain itu yang sifatnya umum, boleh ditambahkan.

**Comment by kassle** [comment]
dokumentasi sudah di buat, lokasinya ada di:
folder = smb://10.0.0.15/documents/hendri/Sucorinvest Doc/unfinish
filename = step-by-step-manual-housekeeping.doc

**Comment by kassle** [comment]
untuk point 1, 2, dan 3 lebih baik di bikin dokumentasi tersendiri (misalnya troubleshooting server). karena kalau untuk issue spesifik housekeeping tapi scope dokumentasi-nya terlalu luas, malah jadinya banyak duplikasi dokumentasi.

**Comment by hendrisulistiono** [comment]
Sudah di cek dan dirapikan , dokumennya ada di smb://10.0.0.15/documents/hendri/Sucorinvest%20Doc/SOP%20&%20Troubleshooting

nama file : Manual Housekeeping.doc
